version: '3.9'

services:
  app:
    image: haskell
    volumes:
      - ./:/app
      - stackCache:/root/.stack/
      - localCache:/app/.stack-work/
    working_dir: /app

volumes:
  stackCache:
  localCache:
