apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: chespirito-production-pipeline-
spec:
  serviceAccountName: tekton-kubectl-service-account
  pipelineRef:
    name: chespirito-production-pipeline
  params:
  - name: repo-url
    value: https://github.com/leandronsp/chespirito.git
  - name: revision
    value: main
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
