#!/bin/bash

NAMESPACE=monitoring

kubectl apply -f ./namespace.yml
kubectl apply -f ./common/
kubectl apply -f ./kube-state-metrics/

kubectl apply -f ./node-exporter/ --namespace $NAMESPACE
kubectl apply -f ./prometheus/ --namespace $NAMESPACE
kubectl apply -f ./grafana/ --namespace $NAMESPACE

kubectl apply -f ./app/
