version: '3.9'
services:
  ruby:
    image: ruby
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
      - gemconfig:/root/.local/share/gem
    working_dir: /app
volumes:
  rubygems:
  gemconfig:
