#!/bin/bash

## Create the response FIFO
rm -f response
mkfifo response

function processRequest() {
  while read line; do
    echo $line
    trline=`echo $line | tr -d '[\r\n]'`

    [ -z "$trline" ] && break

    REQUEST_REGEX='GET\s(.*?)\sHTTP.*?'
    [[ "$trline" =~ $REQUEST_REGEX ]] &&
      REQUEST=$(echo $trline | sed -E "s/$REQUEST_REGEX/\1 \2/")
  done

  [ "$REQUEST" = "GET /" ] && cat
  [ "$CONTENT_TYPE" != "application/text" ] && cat http/005-login/html/get-login.html

  RESPONSE="HTTP/1.1 200\r\n\r\n\r\n</h1>PONG</h1>"
  echo -e $RESPONSE > response
}

echo 'Listening on 3000...'

cat response | nc -lN 3000 | processRequest
