bash:
	@docker-compose run app bash

hello.world:
	@docker-compose run app kotlin hello.kts

compile:
	@docker-compose run app kotlinc hello.kt

hello.world.run:
	@docker-compose run app java HelloKt


